### PR TITLE
Upgrading Ruby to 3.0.2

### PR DESCRIPTION
**Pull request by agbinary**

### CODE REVIEW

**Review by jethroo — APPROVED** [review]
🪄 ✨ 

thanks so much for taking care, also please add a new tag https://github.com/homeday-de/mandrill-api-ruby/tags after merge please ;)

**Review by wjfrey — APPROVED** [review]
Awesome!

**Comment by agbinary** [comment]
> 🪄 ✨
> 
> thanks so much for taking care, also please add a new tag https://github.com/homeday-de/mandrill-api-ruby/tags after merge please ;)

of course! That's the idea

**Review by mimipacheco — APPROVED** [review]
🧡

**Pull request merged**
